// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using adapter.Adapter.Entidades;
using ApiAdapter.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;


namespace ApiAdapter.Data
{
    public partial class AdapterDbContext : DbContext
    {
        public AdapterDbContext()
        {
        }

        public AdapterDbContext(DbContextOptions<AdapterDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Temperatura> Temperatura { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TemperaturaDTO>().Property(p => p.tempID)
       .ValueGeneratedOnAdd();
            modelBuilder.Entity<Temperatura>(entity =>
            {
                entity.Property(e => e.bloque)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.temp)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);

           

        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}