// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjVehiculos.Models
{
    public partial class Calendarizacion
    {
        public int Mes { get; set; }
        public int? UltimoDigitoPlaca { get; set; }
    }
}