// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjVehiculos.Models
{
    public partial class Impuestos
    {
        public int IdImpuesto { get; set; }
        public decimal MultaAtraso { get; set; }
        public decimal ImpuestoPropiedad { get; set; }
        public decimal ImpuestoRodaje { get; set; }
        public decimal TasaAnt { get; set; }
        public decimal TasaPagoAccidentes { get; set; }
        public decimal TasaJuntaGuayaquil { get; set; }
    }
}