// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjVehiculos.Models
{
    public partial class Vehiculo
    {
        public string Placa { get; set; }
        public string TipoVehiculo { get; set; }
        public int AnioFabricacion { get; set; }
        public string PaisOrigen { get; set; }
        public string NombrePropietario { get; set; }
        public decimal Avaluo { get; set; }
        public string Color { get; set; }
        public decimal Cilindraje { get; set; }
        public string Marca { get; set; }
    }
}