// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PryComposite.Models
{
    public partial class FileSystem
    {
        public int Id { get; set; }
        public int IdPadre { get; set; }
        public string Nombre { get; set; }
        public bool EsArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public int Tamanio { get; set; }
    }
}