// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PrjVehiculos.Models;

namespace PrjVehiculos.Data
{
    public partial class VehiculosContext : DbContext
    {
        public VehiculosContext()
        {
        }

        public VehiculosContext(DbContextOptions<VehiculosContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Calendarizacion> Calendarizacion { get; set; }
        public virtual DbSet<Impuestos> Impuestos { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Calendarizacion>(entity =>
            {
                entity.HasKey(e => e.Mes);

                entity.ToTable("Calendarizacion", "matricula");

                entity.Property(e => e.Mes).ValueGeneratedNever();
            });

            modelBuilder.Entity<Impuestos>(entity =>
            {
                entity.HasKey(e => e.IdImpuesto);

                entity.ToTable("Impuestos", "matricula");

                entity.Property(e => e.IdImpuesto).ValueGeneratedNever();

                entity.Property(e => e.ImpuestoPropiedad).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.ImpuestoRodaje).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.MultaAtraso).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.TasaAnt)
                    .HasColumnType("decimal(5, 2)")
                    .HasColumnName("TasaANT");

                entity.Property(e => e.TasaJuntaGuayaquil).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.TasaPagoAccidentes).HasColumnType("decimal(5, 2)");
            });

            modelBuilder.Entity<Vehiculo>(entity =>
            {
                entity.HasKey(e => e.Placa);

                entity.ToTable("Vehiculo", "matricula");

                entity.Property(e => e.Placa)
                    .HasMaxLength(8)
                    .IsUnicode(false);

                entity.Property(e => e.Avaluo).HasColumnType("decimal(8, 2)");

                entity.Property(e => e.Cilindraje).HasColumnType("decimal(4, 2)");

                entity.Property(e => e.Color)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Marca)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.NombrePropietario)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PaisOrigen)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.TipoVehiculo)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}